### ISSUE TITLE
[BUG] <freecadcmd> CLI Not Working

### ISSUE THREAD

**Issue by ThaL3g3nd27** [linuxserver/docker-freecad#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Python scripts do not work in the docker container cli.

Traceback (most recent call last):
  File "<string>", line 8, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lsiopy/bin/activate_this.py'

### Expected Behavior

freecadcmd file.py

python function should run without the gui.

### Steps To Reproduce

https://github.com/ThaL3g3nd27/issue-FreeCad-freecadcmd.git 

### Environment

```markdown
- OS: Ubuntu on WSL
- How docker service was installed: docker compose build

# Use the LinuxServer.io FreeCAD Docker image
FROM lscr.io/linuxserver/freecad:latest

# Set the working directory
WORKDIR /app/
```

### CPU architecture

x86-64

### Docker creation

```bash
version: '3'

services:
  freecad:
    build:
      context: .
    container_name: freecad
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/app/config
      - ./py_scripts:/app/py_scripts
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped
```

### Container logs

```bash
root@a5613fcfb2a4:/app/py_scripts# freecadcmd boxtest.py
Traceback (most recent call last):
  File "<string>", line 8, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/lsiopy/bin/activate_this.py'
FreeCAD 0.20.2, Libs: 0.20.2R
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2022
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##
```

**Comment by thelamer** [comment]
So this got run through on Discord and is a disconnect with our internal wheel logic at LSIO for python the solution was to:

```
sudo apt-get update && sudo apt-get install -y python3-virtualenv
unset VIRTUAL_ENV
```

https://discord.com/channels/354974912613449730/1217968478393470986
